### ISSUE TITLE
Sorry lo.以为github上面写的都是对的，新手，表介意

### ISSUE THREAD

**Issue by AlphaQi** [flyingzhao/tfTCDCN#2]

**Comment by flyingzhao** [comment]
你成功的影响了我的心情。Github只是一个交流的平台，没有人能保证自己的东西是正确的。只有大家一起分享才能共同进步，特别对于论文实现这样的工作，不同人对论文的理解程度是不一样的。如果你觉得你的更好，你可以试着使用Pull request功能，把你的东西分享给别人。还有，没事就喷，而不是共同探讨，这里不是百度贴吧，我也没有义务帮你解决所有的问题，这样的态度不建议来GitHub。本来我给你写了很详细的指导，后来我觉得没有意义删掉了。

**Comment by flyingzhao** [comment]
我发现我自己对傻逼太友好了 @AlphaQi
