### ISSUE TITLE
Prepare Data

### ISSUE THREAD

**Issue by herleeyandi** [flyingzhao/tfTCDCN#2]
Hello can you show me `PrepareData` part?, What happen in `get_next_batch`?
I just guest it should be has 2 .npy files (in case I just want detect landmark) which one has dimension` number_of_dataX3X40X40` and the Landmark with dimension `number_of_dataX10` . But I dont know how to feed the data and what exactly happen in `get_next_batch`.
-Thank you-

**Comment by flyingzhao** [comment]
You can take my code as a reference, then you can write your own implement.

**Comment by herleeyandi** [comment]
I just want to know what exactly should be happening in `get_next_batch("testing", 50)` is it load 50% of your dataset as testing data? or from testing dataset you load until index 50?
What is `for x in range(10000):` 10000 is the epoch of training?
Sorry I am new in tensorflow.
-Thank you-

**Comment by flyingzhao** [comment]
I take 50 pictures as a batch. 10000 is how many times to take 50 pictures.

**Comment by MayankSharma-MS** [comment]
Hi  herleeyandi, 
I am new to tensorflow and trying to get some hands-on. Were you able to get this working?? if yes please update on how to use this. thanks!!
